# Generated by Django 2.1.7 on 2019-04-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movieinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mName', models.CharField(max_length=256)),
                ('mDirectors', models.CharField(max_length=256)),
                ('mActors', models.CharField(max_length=256)),
                ('mType', models.CharField(max_length=50)),
            ],
        ),
    ]
